In [1]:
import numpy as np

In [2]:
list_=['1','2','3','4','5']

In [3]:
array_list=np.array(object=list_)

In [ ]:
Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code
to print the data types of both the variables.

In [7]:
# yes there are difference in the data type of variables list_ and array_list

print(type(list_))

print(type(array_list))

<class 'list'>
<class 'numpy.ndarray'>


In [ ]:
Q2. Write a code to print the data type of each and every element of both the variables list_ and
arra_list.

In [ ]:
Q4. Write a code to find the following characteristics of variable, num_array:
(i) shape
(ii) size

In [12]:
arr1=np.random.randint(1,10,(3,4))
print(arr1)

print(np.shape(arr1))

print(np.size(arr1))

[[8 9 2 6]
 [4 9 2 3]
 [5 7 9 3]]
(3, 4)
12


In [ ]:
Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array
creation function.

In [14]:
arr2=np.zeros((3,3))
print(arr2)

print(np.shape(arr2))

print(np.size(arr2))

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
(3, 3)
9


In [ ]:
Q6. Create an identity matrix of shape (5,5) using numpy functions?

In [16]:
arr3=np.eye(5)
print(arr3)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
